# Generated by Django 2.2.14 on 2020-09-05 20:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20200905_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrent',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, help_text='This price should not be affected after rent started', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='rentdayhistory',
            name='amount',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
