# Generated by Django 2.2.14 on 2020-09-05 20:08

from django.db import migrations

def forwards(apps, schema_editor):
    BookRent = apps.get_model('book', 'BookRent')
    # this is kinda slow, but still ok for not huge amount of objects
    for br in BookRent.objects.all().iterator():
        br.price = br.book.category.price
        br.save(update_fields=('price', ))


def backwards(apps, schema_editor):
    BookRent = apps.get_model('book', 'BookRent')
    BookRent.objects.update(price=None)



class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20200905_2008'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
