# Generated by Django 2.2.14 on 2020-09-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20200906_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentdayhistory',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
