
BOOK_STATUS_PENDING, BOOK_STATUS_CONFIRMED, BOOK_STATUS_IN_USE, BOOK_STATUS_END = range(1, 5)

BOOK_STATUSES = (
    (BOOK_STATUS_PENDING, 'pending'),
    (BOOK_STATUS_CONFIRMED, 'confirmed'),
    (BOOK_STATUS_IN_USE, 'in use'),
    (BOOK_STATUS_END, 'end'),
)
